---
dist: trusty # "Ubuntu Trusty" - has more up-to-date Java & Python
dudo: required

language: java

jdk:
  - oraclejdk8

python:
  - "2.7"

before_install:
  - ls -lthra
  - java -version
  - python --version
  - which pip
  - "pip install --user scipy" # includes numpy
  - "pip install --user scikit-learn"

install:
  - mvn install
  # - mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs # spotbugs goal produces a report target/spotbugsXml.xml
  - mvn com.github.spotbugs:spotbugs-maven-plugin:check # check goal produces a report and produces build failed if bugs
  # the spotbugsXml.xml file is easiest read in a web browser
  # see http://spotbugs.readthedocs.io/en/latest/maven.html and https://spotbugs.github.io/spotbugs-maven-plugin/index.html for more info

script:
  - mvn cobertura:cobertura # for codecov
  - "python src/main/python/edu/ung/phys/trainNetwork.py"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  emails: false
